# Generated by Django 5.2.7 on 2026-01-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='clearance_form',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('department_head', 'Department Head'), ('librarian', 'Librarian'), ('cafeteria', 'Cafeteria'), ('dormitory', 'Dormitory'), ('registrar', 'Registrar')], max_length=50),
        ),
    ]
