# Generated by Django 5.2.7 on 2026-01-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_chatroom_clearance_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='student',
        ),
    ]
