# Generated by Django 5.2.7 on 2026-01-19 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_chatroom_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
