# Generated by Django 5.2.7 on 2026-01-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20260119_0708'),
        ('api', '0007_bankaccount_studentbill'),
    ]

    operations = [
    ]
