# Generated by Django 5.2.7 on 2026-01-20 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_payment_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='verified_by_librarian',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
