# Generated by Django 5.2.7 on 2026-01-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_paymentmethod_studentpayment_paymentverificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='receipt_file',
            field=models.FileField(upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='receipt_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/thumbnails/'),
        ),
    ]
