# Generated by Django 5.2.7 on 2026-01-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_studentpayment_receipt_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceform',
            name='cafeteria_payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='dormitory_payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='library_payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
