# Generated by Django 5.2.7 on 2026-01-21 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_clearanceform_cafeteria_payment_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearanceform',
            name='cafeteria_payment_verified',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='dormitory_payment_verified',
        ),
        migrations.RemoveField(
            model_name='clearanceform',
            name='library_payment_verified',
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='receipt_file',
            field=models.FileField(upload_to='payment_receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='receipt_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/thumbnails/'),
        ),
    ]
