# Generated by Django 5.2.7 on 2026-01-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_clearanceform_cafeteria_payment_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='receipt_file',
            field=models.FileField(upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='receipt_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/thumbnails/'),
        ),
    ]
