# Generated by Django 5.2.7 on 2026-01-22 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_studentpayment_receipt_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='due_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='due_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='original_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='pnr_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Reference Number'),
        ),
        migrations.CreateModel(
            name='CafeteriaDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('library', 'Library'), ('cafeteria', 'Cafeteria'), ('dormitory', 'Dormitory')], max_length=20)),
                ('pnr_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Payment Reference Number')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('other', 'Other')], max_length=20)),
                ('meal_date', models.DateField()),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cafeteria Due',
                'verbose_name_plural': 'Cafeteria Dues',
            },
        ),
        migrations.CreateModel(
            name='DormitoryDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('library', 'Library'), ('cafeteria', 'Cafeteria'), ('dormitory', 'Dormitory')], max_length=20)),
                ('pnr_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Payment Reference Number')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('room_number', models.CharField(max_length=20)),
                ('damage_type', models.CharField(choices=[('window', 'Broken Window'), ('door', 'Door Damage'), ('bed', 'Bed Damage'), ('wall', 'Wall Damage'), ('floor', 'Floor Damage'), ('electricity', 'Electrical Issue'), ('key', 'Missing Key'), ('furniture', 'Furniture Damage'), ('other', 'Other Damage')], max_length=20)),
                ('damage_description', models.TextField()),
                ('reported_date', models.DateField()),
                ('repair_deadline', models.DateField()),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dormitory Due',
                'verbose_name_plural': 'Dormitory Dues',
            },
        ),
        migrations.CreateModel(
            name='LibraryDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('library', 'Library'), ('cafeteria', 'Cafeteria'), ('dormitory', 'Dormitory')], max_length=20)),
                ('pnr_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Payment Reference Number')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('book_title', models.CharField(max_length=200)),
                ('book_category', models.CharField(choices=[('textbook', 'Textbook'), ('reference', 'Reference Book'), ('journal', 'Journal'), ('thesis', 'Thesis'), ('other', 'Other')], max_length=20)),
                ('book_id', models.CharField(max_length=50)),
                ('borrow_date', models.DateField()),
                ('return_due_date', models.DateField()),
                ('overdue_days', models.IntegerField(default=0)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Library Due',
                'verbose_name_plural': 'Library Dues',
            },
        ),
        migrations.CreateModel(
            name='PNRPaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_number', models.CharField(max_length=50, unique=True)),
                ('due_model', models.CharField(choices=[('LibraryDue', 'Library Due'), ('CafeteriaDue', 'Cafeteria Due'), ('DormitoryDue', 'Dormitory Due')], max_length=50)),
                ('due_id', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pnr_links', to='api.studentpayment')),
            ],
        ),
    ]
