# Generated by Django 5.2.7 on 2026-01-22 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_studentpayment_due_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormitorydue',
            name='student',
        ),
        migrations.RemoveField(
            model_name='librarydue',
            name='student',
        ),
        migrations.RemoveField(
            model_name='pnrpaymentlink',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='due_description',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='due_type',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='original_due_amount',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='pnr_number',
        ),
        migrations.DeleteModel(
            name='CafeteriaDue',
        ),
        migrations.DeleteModel(
            name='DormitoryDue',
        ),
        migrations.DeleteModel(
            name='LibraryDue',
        ),
        migrations.DeleteModel(
            name='PNRPaymentLink',
        ),
    ]
