# Generated by Django 5.2.7 on 2026-01-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_dormitorydue_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcontrol',
            name='is_cafeteria_open',
            field=models.BooleanField(default=True, verbose_name='Cafeteria Open'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_department_head_open',
            field=models.BooleanField(default=True, verbose_name='Department Head Open'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_dormitory_open',
            field=models.BooleanField(default=True, verbose_name='Dormitory Open'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_librarian_open',
            field=models.BooleanField(default=True, verbose_name='Librarian Open'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_payment_open',
            field=models.BooleanField(default=True, verbose_name='Payment System Open'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_registrar_open',
            field=models.BooleanField(default=True, verbose_name='Registrar Open'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_student_open',
            field=models.BooleanField(default=True, verbose_name='Student Portal Open'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='maintenance_message',
            field=models.TextField(blank=True, null=True, verbose_name='Maintenance Message'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='maintenance_title',
            field=models.CharField(blank=True, default='System Under Maintenance', max_length=200, null=True, verbose_name='Maintenance Title'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='scheduled_maintenance_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Maintenance End'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='scheduled_maintenance_message',
            field=models.TextField(blank=True, null=True, verbose_name='Scheduled Maintenance Message'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='scheduled_maintenance_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Maintenance Start'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='show_maintenance_page',
            field=models.BooleanField(default=True, verbose_name='Show Maintenance Page'),
        ),
    ]
