# Generated by Django 5.2.7 on 2026-01-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_systemcontrol_is_cafeteria_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemcontrol',
            name='is_cafeteria_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='is_department_head_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='is_dormitory_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='is_librarian_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='is_payment_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='is_registrar_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='is_student_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='maintenance_message',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='maintenance_title',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='scheduled_maintenance_end',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='scheduled_maintenance_message',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='scheduled_maintenance_start',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='show_maintenance_page',
        ),
        migrations.AddField(
            model_name='systemcontrolrequest',
            name='is_cafeteria_open',
            field=models.BooleanField(default=True, verbose_name='Cafeteria Access'),
        ),
        migrations.AddField(
            model_name='systemcontrolrequest',
            name='is_department_head_open',
            field=models.BooleanField(default=True, verbose_name='Department Head Access'),
        ),
        migrations.AddField(
            model_name='systemcontrolrequest',
            name='is_dormitory_open',
            field=models.BooleanField(default=True, verbose_name='Dormitory Access'),
        ),
        migrations.AddField(
            model_name='systemcontrolrequest',
            name='is_librarian_open',
            field=models.BooleanField(default=True, verbose_name='Librarian Access'),
        ),
        migrations.AddField(
            model_name='systemcontrolrequest',
            name='is_payment_open',
            field=models.BooleanField(default=True, verbose_name='Payment System Access'),
        ),
        migrations.AddField(
            model_name='systemcontrolrequest',
            name='is_registrar_open',
            field=models.BooleanField(default=True, verbose_name='Registrar Access'),
        ),
        migrations.AddField(
            model_name='systemcontrolrequest',
            name='is_student_open',
            field=models.BooleanField(default=True, verbose_name='Student Access'),
        ),
    ]
