# Generated by Django 5.2.7 on 2026-01-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_systemcontrol_is_cafeteria_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcontrolrequest',
            name='show_maintenance_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemcontrolrequest',
            name='is_cafeteria_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemcontrolrequest',
            name='is_department_head_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemcontrolrequest',
            name='is_dormitory_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemcontrolrequest',
            name='is_librarian_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemcontrolrequest',
            name='is_payment_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemcontrolrequest',
            name='is_registrar_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemcontrolrequest',
            name='is_student_open',
            field=models.BooleanField(default=False),
        ),
    ]
