# Generated by Django 5.2.7 on 2026-01-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_systemcontrolrequest_show_maintenance_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemcontrolrequest',
            name='is_cafeteria_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrolrequest',
            name='is_department_head_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrolrequest',
            name='is_dormitory_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrolrequest',
            name='is_librarian_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrolrequest',
            name='is_payment_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrolrequest',
            name='is_registrar_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrolrequest',
            name='is_student_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrolrequest',
            name='show_maintenance_page',
        ),
        migrations.AlterField(
            model_name='systemcontrol',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
