# Generated by Django 5.2.7 on 2026-01-25 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_systemcontrolrequest_is_cafeteria_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='clearance_form',
            field=models.ForeignKey(blank=True, help_text='Linked clearance form requiring this payment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.clearanceform'),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='note',
            field=models.TextField(blank=True, help_text='Payment purpose/reference', null=True),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='status',
            field=models.CharField(choices=[('pending_department', 'Pending Department'), ('approved_department', 'Approved by Department'), ('approved_library', 'Approved by Library'), ('approved_cafeteria', 'Approved by Cafeteria'), ('approved_dormitory', 'Approved by Dormitory'), ('Cleared by Registrar', 'Cleared by Registrar'), ('rejected', 'Rejected'), ('pending_resubmission', 'Pending Resubmission'), ('requires_library_payment', 'Requires Library Payment'), ('requires_cafeteria_payment', 'Requires Cafeteria Payment'), ('requires_dormitory_payment', 'Requires Dormitory Payment')], default='pending_department', max_length=30),
        ),
    ]
