# Generated by Django 5.2.7 on 2026-01-28 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_studentpayment_clearance_form_studentpayment_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='Student ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('batch_year', models.CharField(blank=True, max_length=4, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='api.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='api.department')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Record',
                'verbose_name_plural': 'Student Records',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
