# Generated by Django 5.2.7 on 2026-01-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_studentrecords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRecords',
        ),
    ]
