# Generated by Django 5.2.7 on 2026-01-29 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_chatroom_options_chatroom_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('department_head', 'Department Head'), ('librarian', 'Librarian'), ('cafeteria', 'Cafeteria'), ('dormitory', 'Dormitory'), ('registrar', 'Registrar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='department',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='last_message_time',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='specific_staff',
        ),
    ]
