# Generated by Django 5.2.7 on 2026-01-29 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_chatroom_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-last_message_time', '-updated_at']},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='specific_staff',
            field=models.ForeignKey(blank=True, help_text='Specific staff member for 1:1 chat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('student_department_head', 'Student - Department Head'), ('student_librarian', 'Student - Librarian'), ('student_cafeteria', 'Student - Cafeteria'), ('student_dormitory', 'Student - Dormitory'), ('student_registrar', 'Student - Registrar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('student', 'room_type', 'department')},
        ),
    ]
