# Generated by Django 5.2.7 on 2026-01-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_chatroom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('payment_required', 'Payment Required'), ('system', 'System'), ('chat', 'Chat')], default='info', max_length=30),
        ),
    ]
