# Generated by Django 5.2.7 on 2026-01-30 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidStudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_of_admission', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_registered', models.BooleanField(default=False)),
                ('csv_file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('registered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_registered_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valid Student Record',
                'verbose_name_plural': 'Valid Student Records',
                'ordering': ['id_number'],
            },
        ),
    ]
