# Generated by Django 5.2.7 on 2026-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_validstudentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validstudentrecord',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='validstudentrecord',
            index=models.Index(fields=['id_number'], name='api_validst_id_numb_dfb02a_idx'),
        ),
        migrations.AddIndex(
            model_name='validstudentrecord',
            index=models.Index(fields=['status'], name='api_validst_status_e1e0ec_idx'),
        ),
        migrations.AddIndex(
            model_name='validstudentrecord',
            index=models.Index(fields=['is_registered'], name='api_validst_is_regi_bdec89_idx'),
        ),
    ]
