# Generated by Django 5.2.7 on 2026-01-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_validstudentrecord_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidStudentRecord',
        ),
    ]
