# Generated by Django 5.2.7 on 2026-01-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_csvstudentupload_authorizedstudent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorizedstudent',
            unique_together={('id_number',)},
        ),
        migrations.AlterField(
            model_name='authorizedstudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
