# Generated by Django 5.2.7 on 2026-01-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_authorizedstudent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemcontrol',
            options={'verbose_name': 'System Control', 'verbose_name_plural': 'System Control'},
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='allowed_days',
            field=models.CharField(blank=True, help_text='Comma-separated day numbers (0=Sunday, 1=Monday, etc.). Leave empty for all days.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='allowed_months',
            field=models.CharField(blank=True, help_text='Comma-separated month numbers (1-12). Leave empty for all months.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='daily_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Daily End Time'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='daily_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Daily Start Time'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='System End Date'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_cafeteria_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_department_head_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_dormitory_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_librarian_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_payment_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_registrar_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_student_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='maintenance_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='maintenance_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='scheduled_maintenance_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='scheduled_maintenance_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='scheduled_maintenance_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='show_maintenance_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='System Start Date'),
        ),
    ]
