# Generated by Django 5.2.7 on 2026-01-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_systemcontrol_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemcontrol',
            options={},
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='allowed_days',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='allowed_months',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='daily_end_time',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='daily_start_time',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='is_cafeteria_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='is_department_head_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='is_dormitory_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='is_librarian_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='is_payment_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='is_registrar_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='is_student_open',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='maintenance_message',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='maintenance_title',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='scheduled_maintenance_end',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='scheduled_maintenance_message',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='scheduled_maintenance_start',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='show_maintenance_page',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='start_date',
        ),
    ]
