# Generated by Django 5.2.7 on 2026-01-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_systemcontrol_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcontrol',
            name='is_cafeteria_open',
            field=models.BooleanField(default=True, verbose_name='Cafeteria Module'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_department_head_open',
            field=models.BooleanField(default=True, verbose_name='Department Head Module'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_dormitory_open',
            field=models.BooleanField(default=True, verbose_name='Dormitory Module'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_librarian_open',
            field=models.BooleanField(default=True, verbose_name='Librarian Module'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_payment_open',
            field=models.BooleanField(default=True, verbose_name='Payment Module'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_registrar_open',
            field=models.BooleanField(default=True, verbose_name='Registrar Module'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_student_open',
            field=models.BooleanField(default=True, verbose_name='Student Module'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='maintenance_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='maintenance_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='scheduled_maintenance_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='scheduled_maintenance_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='scheduled_maintenance_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='show_maintenance_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemcontrol',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='System Open'),
        ),
    ]
