# Generated by Django 5.2.7 on 2026-02-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_paymentmethod_options_paymentmethod_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Payment Method Name'),
        ),
    ]
