# Generated by Django 5.2.7 on 2026-02-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_paymentmethod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
