# Generated by Django 5.2.7 on 2026-02-03 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_paymentmethod_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='bank_name',
        ),
    ]
