# Generated by Django 5.2.7 on 2026-02-04 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_paymentmethod_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=120, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('program_level', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('department_head_name', models.CharField(max_length=255)),
                ('department_head_role', models.CharField(max_length=255)),
                ('department_head_status', models.CharField(max_length=50)),
                ('librarian_name', models.CharField(max_length=255)),
                ('librarian_role', models.CharField(max_length=255)),
                ('librarian_status', models.CharField(max_length=50)),
                ('cafeteria_name', models.CharField(max_length=255)),
                ('cafeteria_role', models.CharField(max_length=255)),
                ('cafeteria_status', models.CharField(max_length=50)),
                ('dormitory_name', models.CharField(max_length=255)),
                ('dormitory_role', models.CharField(max_length=255)),
                ('dormitory_status', models.CharField(max_length=50)),
                ('registrar_name', models.CharField(max_length=255)),
                ('registrar_role', models.CharField(max_length=255)),
                ('registrar_status', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='api.clearanceform')),
            ],
        ),
    ]
