# Generated by Django 5.2.7 on 2026-02-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_clearancecertificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClearanceCertificate',
        ),
    ]
