# Generated by Django 5.2.7 on 2026-02-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_systemcontrol_created_at_systemcontrol_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceform',
            name='cafeteria_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='cafeteria_approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='department_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='department_approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='dormitory_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='dormitory_approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='library_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='library_approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='registrar_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='registrar_approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
