# Generated by Django 5.2.7 on 2026-02-04 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_clearanceform_cafeteria_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=100, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('clearance_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='api.clearanceform')),
            ],
        ),
    ]
