# Generated by Django 5.2.7 on 2026-02-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
