# Generated by Django 5.2.7 on 2026-02-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_message_audio_file_message_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('departmenthead', 'Department Head'), ('librarian', 'Librarian'), ('cafeteria', 'Cafeteria'), ('dormitory', 'Dormitory'), ('registrar', 'Registrar')], max_length=30),
        ),
    ]
