# Generated by Django 5.2.7 on 2026-02-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceform',
            name='campuspolice_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='campuspolice_approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='campuspolice_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='coastsharing_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='coastsharing_approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='coastsharing_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='dopcoordinator_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='dopcoordinator_approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='dopcoordinator_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='psychology_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='psychology_approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='psychology_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='sportmaster_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='sportmaster_approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='sportmaster_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='studentaffairs_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='studentaffairs_approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='studentaffairs_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_campuspolice_open',
            field=models.BooleanField(default=True, verbose_name='Campus Police Module'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_coastsharing_open',
            field=models.BooleanField(default=True, verbose_name='Coast Sharing Module'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_dopcoordinator_open',
            field=models.BooleanField(default=True, verbose_name='DOP Coordinator Module'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_psychology_open',
            field=models.BooleanField(default=True, verbose_name='Psychology Module'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_sportmaster_open',
            field=models.BooleanField(default=True, verbose_name='Sport Master Module'),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='is_studentaffairs_open',
            field=models.BooleanField(default=True, verbose_name='Student Affairs Module'),
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='status',
            field=models.CharField(choices=[('pending_department', 'Pending Department'), ('approved_department', 'Approved by Department'), ('approved_library', 'Approved by Library'), ('approved_cafeteria', 'Approved by Cafeteria'), ('approved_psychology', 'Approved by Psychology'), ('approved_sportmaster', 'Approved by Sport Master'), ('approved_campuspolice', 'Approved by Campus Police'), ('approved_coastsharing', 'Approved by Coast Sharing'), ('approved_dopcoordinator', 'Approved by DOP Coordinator'), ('approved_studentaffairs', 'Approved by Student Affairs'), ('approved_dormitory', 'Approved by Dormitory'), ('Cleared by Registrar', 'Cleared by Registrar'), ('rejected', 'Rejected'), ('pending_resubmission', 'Pending Resubmission'), ('requires_library_payment', 'Requires Library Payment'), ('requires_cafeteria_payment', 'Requires Cafeteria Payment'), ('requires_psychology_payment', 'Requires Psychology Payment'), ('requires_sportmaster_payment', 'Requires Sport Master Payment'), ('requires_campuspolice_payment', 'Requires Campus Police Payment'), ('requires_coastsharing_payment', 'Requires Coast Sharing Payment'), ('requires_dopcoordinator_payment', 'Requires DOP Coordinator Payment'), ('requires_studentaffairs_payment', 'Requires Student Affairs Payment'), ('requires_dormitory_payment', 'Requires Dormitory Payment')], default='pending_department', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='department_type',
            field=models.CharField(choices=[('library', 'Library'), ('cafeteria', 'Cafeteria'), ('psychology', 'Psychology'), ('sportmaster', 'Sport Master'), ('campuspolice', 'Campus Police'), ('coastsharing', 'Coast Sharing'), ('dopcoordinator', 'DOP Coordinator'), ('studentaffairs', 'Student Affairs'), ('dormitory', 'Dormitory'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('departmenthead', 'Department Head'), ('librarian', 'Librarian'), ('cafeteria', 'Cafeteria'), ('psychology', 'Psychology'), ('sportmaster', 'Sport Master'), ('campuspolice', 'Campus Police'), ('coastsharing', 'Coast Sharing'), ('dopcoordinator', 'DOP Coordinator'), ('studentaffairs', 'Student Affairs'), ('dormitory', 'Dormitory'), ('registrar', 'Registrar'), ('admin', 'Admin')], max_length=30),
        ),
    ]
