# Generated by Django 5.2.7 on 2026-03-02 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_clearanceform_campuspolice_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Building code (e.g., BLK-A, D-101)', max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('capacity', models.IntegerField(default=0, help_text='Maximum number of students')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='student_building_code',
            field=models.CharField(blank=True, help_text='Building code for quick filtering', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='assigned_buildings',
            field=models.ManyToManyField(blank=True, help_text='Buildings this dormitory staff member manages', related_name='dormitory_staff', to='api.building'),
        ),
        migrations.AddField(
            model_name='clearanceform',
            name='student_building',
            field=models.ForeignKey(blank=True, help_text='Building where the student resides', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_buildings', to='api.building'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_buildings',
            field=models.ManyToManyField(blank=True, help_text='Buildings this dormitory staff member manages', related_name='assigned_staff', to='api.building'),
        ),
        migrations.AddField(
            model_name='user',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Dormitory building assigned to the student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_students', to='api.building'),
        ),
    ]
