# Generated by Django 5.2.7 on 2026-03-02 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_building_clearanceform_student_building_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='managing_staff',
            field=models.ManyToManyField(blank=True, help_text='Dormitory staff assigned to manage this building', related_name='managed_buildings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_buildings',
            field=models.ManyToManyField(blank=True, help_text='Buildings this dormitory staff member manages', related_name='students_in_building', to='api.building'),
        ),
    ]
