# Generated by Django 5.2.7 on 2026-03-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_building_managing_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='managing_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_buildings',
            field=models.ManyToManyField(blank=True, help_text='Buildings this dormitory staff member manages', related_name='assigned_staff', to='api.building'),
        ),
    ]
