# Generated by Django 5.2.7 on 2026-03-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_remove_building_managing_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearanceform',
            old_name='coastsharing_approved_at',
            new_name='cooperationsharing_approved_at',
        ),
        migrations.RenameField(
            model_name='clearanceform',
            old_name='coastsharing_approved_by',
            new_name='cooperationsharing_approved_by',
        ),
        migrations.RenameField(
            model_name='clearanceform',
            old_name='coastsharing_note',
            new_name='cooperationsharing_note',
        ),
        migrations.AlterField(
            model_name='clearanceform',
            name='status',
            field=models.CharField(choices=[('pending_department', 'Pending Department'), ('approved_department', 'Approved by Department'), ('approved_library', 'Approved by Library'), ('approved_cafeteria', 'Approved by Cafeteria'), ('approved_psychology', 'Approved by Psychology'), ('approved_sportmaster', 'Approved by Sport Master'), ('approved_campuspolice', 'Approved by Campus Police'), ('approved_cooperationsharing', 'Approved by Cooperation Sharing'), ('approved_dopcordinator', 'Approved by DOP Cordinator'), ('approved_studentaffairs', 'Approved by Student Affairs'), ('approved_dormitory', 'Approved by Dormitory'), ('Cleared by Registrar', 'Cleared by Registrar'), ('rejected', 'Rejected'), ('pending_resubmission', 'Pending Resubmission'), ('requires_library_payment', 'Requires Library Payment'), ('requires_cafeteria_payment', 'Requires Cafeteria Payment'), ('requires_psychology_payment', 'Requires Psychology Payment'), ('requires_sportmaster_payment', 'Requires Sport Master Payment'), ('requires_campuspolice_payment', 'Requires Campus Police Payment'), ('requires_cooperationsharing_payment', 'Requires Cooperation Sharing Payment'), ('requires_dopcordinator_payment', 'Requires DOP Cordinator Payment'), ('requires_studentaffairs_payment', 'Requires Student Affairs Payment'), ('requires_dormitory_payment', 'Requires Dormitory Payment')], default='pending_department', max_length=50),
        ),
    ]
