# Generated by Django 5.2.7 on 2026-03-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_rename_coastsharing_approved_at_clearanceform_cooperationsharing_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='authorizedstudent',
            name='middle_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, help_text="Student's middle name (required)", max_length=100, null=True, verbose_name='Middle Name'),
        ),
    ]
