# Generated by Django 5.2.7 on 2026-03-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_user_options_authorizedstudent_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RemoveField(
            model_name='authorizedstudent',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
    ]
