# Generated by Django 5.2.7 on 2026-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_user_active_session_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_session_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_session_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
        migrations.AddField(
            model_name='user',
            name='sha256_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
