# Generated by Django 5.2.7 on 2026-05-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_remove_user_active_session_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sha256_password',
        ),
    ]
